# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: odds 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "odds"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Mike Harris"]
  s.date = "2014-04-01"
  s.description = "odds"
  s.email = "mharris717@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "input/bets.csv",
    "input/sims.csv",
    "lib/odds.rb",
    "lib/odds/algorithms/correlated_kelly.rb",
    "lib/odds/algorithms/genetic.rb",
    "lib/odds/algorithms/kelly.rb",
    "lib/odds/algorithms/parlay_utility.rb",
    "lib/odds/bet.rb",
    "lib/odds/ext/hash.rb",
    "lib/odds/ext/map_special.rb",
    "lib/odds/ext/math.rb",
    "lib/odds/ext/numeric.rb",
    "lib/odds/ext/object.rb",
    "lib/odds/ext/rand.rb",
    "lib/odds/ext/string.rb",
    "lib/odds/ext/to_odds.rb",
    "lib/odds/lines.rb",
    "lib/odds/odds.rb",
    "lib/odds/parlay.rb",
    "lib/odds/special/combination_parlay.rb",
    "lib/odds/special/load_sims.rb",
    "odds.gemspec",
    "spec/algorithms/correlated_kelly_spec.rb",
    "spec/algorithms/kelly_spec.rb",
    "spec/bet_spec.rb",
    "spec/lines_spec.rb",
    "spec/odds_spec.rb",
    "spec/parlay_spec.rb",
    "spec/spec_helper.rb",
    "spec/special/combination_parlay_spec.rb",
    "vol/kelly_sim.rb",
    "vol/parlay_utility_test.rb",
    "vol/parlays_as_horses.rb"
  ]
  s.homepage = "http://github.com/mharris717/odds"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "odds"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<rdoc>, [">= 0"])
      s.add_runtime_dependency(%q<bundler>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<guard>, [">= 0"])
      s.add_runtime_dependency(%q<guard-rspec>, [">= 0"])
      s.add_runtime_dependency(%q<guard-spork>, [">= 0"])
      s.add_runtime_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_runtime_dependency(%q<lre>, [">= 0"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<mharris_ext>, [">= 0"])
      s.add_runtime_dependency(%q<mongoid_gem_config>, [">= 0"])
      s.add_runtime_dependency(%q<define_task>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<guard-spork>, [">= 0"])
      s.add_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_dependency(%q<lre>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<mharris_ext>, [">= 0"])
      s.add_dependency(%q<mongoid_gem_config>, [">= 0"])
      s.add_dependency(%q<define_task>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<guard-spork>, [">= 0"])
    s.add_dependency(%q<rb-fsevent>, [">= 0"])
    s.add_dependency(%q<lre>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<mharris_ext>, [">= 0"])
    s.add_dependency(%q<mongoid_gem_config>, [">= 0"])
    s.add_dependency(%q<define_task>, [">= 0"])
  end
end

